const actionTypes = {}

actionTypes.VERIFY_USER_STARTED = "VERIFY_USER_STARTED"

actionTypes.VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS"

actionTypes.VERIFY_USER_FAILED= "VERIFY_USER_FAILED"

actionTypes.FOLLOW_USER = "FOLLOW_USER"

actionTypes.UNFOLLOW_USER = "UNFOLLOW_USER"

actionTypes.SET_BODY_CARD = "SET_BODY_CARD"

actionTypes.SET_BODY_CARD_FAILED = "SET_BODY_CARD_FAILED"

actionTypes.SET_FIRST_BODY_CARD = "SET_FIRST_BODY_CARD"

actionTypes.SET_BODY_CARD_AUTHOR = "SET_BODY_CARD_AUTHOR"

actionTypes.SET_BODY_CARD_BLOB = "SET_BODY_CARD_BLOB"

actionTypes.DELETE_ALL_BODY_CARD_DATA = "DELETE_ALL_BODY_CARD_DATA"

actionTypes.SET_ARTICLE_DATA = "SET_ARTICLE_DATA"

actionTypes.SET_ARTICLE_BLOB = "SET_ARTICLE_BLOB"

actionTypes.DELETE_ALL_ARTICLE_DATA = "DELETE_ALL_ARTICLE_DATA"

actionTypes.SET_COMMENTS = "SET_COMMENTS"

actionTypes.DELETE_COMMENTS = "DELETE_COMMENTS"

module.exports = actionTypes